export const FETCH_MENUS = 'FETCH_MENUS'
export const ORDER_FOOD = 'ORDER_FOOD'
export const GET_SALDO = 'GET_SALDO'
export const CREATE_ORDER = 'CREATE_ORDER'
export const FIND_USER = 'FIND_USER'
export const SCAN_QR = 'SCAN_QR'
export const ERROR = 'ERROR'